### ISSUE TITLE
NoClassDefFoundError me.relex.circleindicator.R$animator

### ISSUE THREAD

**Issue by gunhansancar** [ongakuer/CircleIndicator#31]
Hello I can compile the project without any problems, however, when I run the application it directly crashes and gives the following exception on Android 4.2 devices.

Btw android 5.0 and above devices works perfectly.

Do you have any idea how to which this issue?

Caused by: java.lang.NoClassDefFoundError: me.relex.circleindicator.R$animator
            at me.relex.circleindicator.CircleIndicator.<init>(CircleIndicator.java:25)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:594)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:255)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)

**Comment by ongakuer** [comment]
Here's some advice, maybe can work:
1. Upgrade Android SDK Build-tools / Android Gradle Plugin /  Android SDK to latest version.
2. Disable Gradle offline mode 
3. Clean Project

If the error still exists, you can try to import library module or source codes to your project...

**Comment by gunhansancar** [comment]
Thank you for your quick reply.
It turned out that the issue is related to multidex enabled setting.
Android 5.0 above internally has com.android.support:multidex library however, below android 5.0 it must be added to  gradle to compile com.android.support:multidex library.

So thank you for your time.

**Comment by ongakuer** [comment]
Thanks for sharing.
