### ISSUE TITLE
Incompatible to use with infinity viewpager scroll

### ISSUE THREAD

**Issue by azizimusa** [ongakuer/CircleIndicator#46]
I tried to use with https://github.com/imbryk/LoopingViewPager. But, it crash when viewpager current item is on last child, and try to looping to 1st child.

This is error I received :

> E/MessageQueue-JNI: java.lang.NullPointerException
                                                                                    at me.relex.circleindicator.CircleIndicator$1.onPageSelected(CircleIndicator.java:185)
                                                                                    at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1794)
                                                                                    at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:569)
                                                                                    at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:553)
                                                                                    at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2102)
                                                                                    at android.view.View.dispatchTouchEvent(View.java:7690)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2066)
                                                                                    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
                                                                                    at android.app.Activity.dispatchTouchEvent(Activity.java:2457)
                                                                                    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2014)
                                                                                    at android.view.View.dispatchPointerEvent(View.java:7870)
                                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3919)
                                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3808)
                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3406)
                                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3456)
                                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3425)
                                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3510)
                                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3433)
                                                                                    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3567)
                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3406)
                                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3456)
                                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3425)
                                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3433)
                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3406)
                                                                                    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5520)
                                                                                    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5500)
                                                                                    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5471)
                                                                                	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java

**Comment by LangleyChang** [comment]
#42 
Redundant issue.
