### ISSUE TITLE
Error inflating class me.relex.circleindicator.CircleIndicator

### ISSUE THREAD

**Issue by deepak-2016** [ongakuer/CircleIndicator#47]
After adding multiDexEnabled true in my project i am getting this error below is the complete log. And also this code is running on emulator but not on real device

`02-22 18:10:25.857    6962-6962/com.development.ngh.happyhours E/dalvikvm﹕ Could not find class 'me.relex.circleindicator.CircleIndicator$ReverseInterpolator', referenced from method me.relex.circleindicator.CircleIndicator.checkIndicatorConfig
02-22 18:10:25.927    6962-6962/com.development.ngh.happyhours E/AndroidRuntime﹕ FATAL EXCEPTION: main
    android.view.InflateException: Binary XML file line #34: Error inflating class me.relex.circleindicator.CircleIndicator
            at android.view.LayoutInflater.createView(LayoutInflater.java:619)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at com.development.ngh.happyhours.fragments.PartyFragment.onCreateView(PartyFragment.java:114)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
            at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
            at android.view.View.measure(View.java:16482)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:681)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
            at android.view.View.measure(View.java:16482)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
            at android.view.View.measure(View.java:16482)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:720)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:592)
            at android.view.View.measure(View.java:16482)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:16482)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:720)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:592)
            at android.view.View.measure(View.java:16482)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2560)
            at android.view.View.measure(View.java:16482)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2195)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1340)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1551)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1237)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5162)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
            at android.view.Choreographer.doFrame(Choreographer.java:561)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5317)
            at java.lang.reflect.Method.invokeNat
`

**Comment by ongakuer** [comment]
https://github.com/ongakuer/CircleIndicator/issues/31
