### ISSUE TITLE
Null pointer 

### ISSUE THREAD

**Issue by JamalMuhammad** [ongakuer/CircleIndicator#53]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setBackgroundResource(int)' on a null object reference
	at me.relex.circleindicator.CircleIndicator$1.onPageSelected(CircleIndicator.java:179)
	at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1862)
	at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:625)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:609)
	at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2174)
	at android.view.View.dispatchTouchEvent(View.java:8400)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2427)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2159)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2173)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2390)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1741)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2827)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2351)
	at android.view.View.dispatchPointerEvent(View.java:8590)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4104)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3970)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3494)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3547)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3513)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3623)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3521)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3680)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3494)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3547)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3513)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3521)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3494)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5799)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5773)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5744)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5922)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5354)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by ongakuer** [comment]
#51
